on:
  push:
    branches:
      - main
  pull_request:

name: CI (without module system)

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "4.0.0"
          - "4.1.0"
          - "4.2.0"
          - "4.3.0"
          - "4.4.0"
          - "4.5.0"
          - "4.6.0"
          - "4.7.0"
          - "4.8.0"
          - "4.9.0"
          - "4.10.0"
          - "4.11.0"
          - "4.12.0"
          - "4.13.0"
          - "4.14.0"
          - "4.15.0"
          - "4.16.0"
          - "4.17.0"
          - "4.18.0"
          - "4.19.0"
          - "4.20.0"
          - "4.20.1"
          - "4.21.0"
          - "4.22.0"
          - "4.23.0"
          - "4.24.0-rc1"
          - "nightly-2025-09-26"

        platform:
          - os: nscloud-ubuntu-22.04-amd64-8x16
            installer: |
              curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
        # Mac runners are rare and expensive, so spot-check that the
        # subprocess support seems OK but be less thorough
        include:
          - toolchain: "4.9.1"
            platform:
              os: macos-latest
              installer: |
                curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
          - toolchain: "4.8.0"
            platform:
              os: macos-latest
              installer: |
                brew install elan-init
          - toolchain: "4.3.0"
            platform:
              os: macos-latest
              installer: |
                brew install elan-init
    name: Build and test (${{ matrix.platform.os }}, ${{ matrix.platform.installer}}, ${{ matrix.toolchain}})
    uses: "./.github/workflows/run-ci.yml"
    with:
      toolchain: ${{ matrix.toolchain }}
      os: ${{ matrix.platform.os }}
      installer: ${{ matrix.platform.installer }}
      module-system: false
      
